name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode-16.0.0.app/Contents/Developer

jobs:
  test_humorAPIService:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Swift version
        run: swift --version

      - name: Set Swift tools version
        run: swift package tools-version --set 5.5

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v
